### ISSUE TITLE
No context menu/toast pop-ups

### ISSUE THREAD

**Issue by bobpullen** [nishanths/what-s-playing#4]
Hi,

Using v.1.5.0 with a corporately administered installation of Firefox 32.0, and despite the extension being installed and all appearing as expected in the add-ons tab, I don't see any toast notifications when using Spotify Web Player (in a pinned tab), and neither do I see a Now Playing context menu option when right-clicking within Firefox.

Any suggestions? I have Firefox 39 installed on a separate machine with the same version of the extension, and that behaves as I'd expect.

Any suggestions on how to troubleshoot why it's not working on my Firefox 32.0 install?

Thanks.

**Comment by nishanths** [comment]
Thanks for reporting.

It might be because of the [cfx to jpm port](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/cfx_to_jpm). Can you check if an older version (v1.4.x or below) works?

Also, is the Firefox 32.0 on Windows, Mac, or Linux?

**Comment by bobpullen** [comment]
Thanks Nishanth,

Uninstalled 1.5.0 and installed 1.4.2 and both the context menu and toast pop-up are back. It's a Windows 7 x64 machine BTW.

Have closed the issue as I assume our admins will get round to upgrading to FF38+ at some point. I'll continue to use 1.4.2 in the interim and disable automatic updating.
